language: android

android:
    components:
        - tools
        - tools
        - platform-tools
        - build-tools-25.0.2
        - android-25
        - extra

jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew
 
script: 
  - ./gradlew clean assembleRelease
